### ISSUE TITLE
Not maintained anymore? Last update was 2 months ago

### ISSUE THREAD

**Issue by rafa-9** [deviint/onlyfans-dynamic-rules#13]
@deviint  Is this repo not maintained anymore? OF seems to have changed dynamic rules today.

**Comment by Tg00174** [comment]
same issue

**Comment by xafable** [comment]
Similar.Returns an error "Please refresh the page"

**Comment by Manual3661** [comment]
This change only happened about 24 hours ago, no update was needed in the other 2 months. Maybe the project is abandoned, maybe not but it's too soon to tell.

In any case, I have a quick fix in a NodeJS/Typescript example. It's a bit rough but it works with the current revision

```ts
import { createHash } from 'crypto';

async function generateHeaders(fullUrl: string, userId: string) {
  const dynamicRules = await getDynamicRules();
  const time = +new Date()
  const url = new URL(fullUrl)
  const msg = [
      dynamicRules["static_param"],
      time,
      url.pathname + url.search,
      userId
  ].join("\n")
  const shaHash = createHash('sha1').update(msg).digest('hex');

  const checksum = createChecksum(shaHash);
  const sign = [dynamicRules["start"], shaHash, checksum, dynamicRules["end"]].join(":")
  // output: {sign, time}
  return {sign, time};
}

async function getDynamicRules(): Promise<any> {
  const body = await fetch('https://raw.githubusercontent.com/deviint/onlyfans-dynamic-rules/main/dynamicRules.json');
  let dynamicRules = await body.json();
  if (dynamicRules.revision !== '202406051438-9d39aa517c') {
    dynamicRules.start = '24650';
    dynamicRules.static_param = 'RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y';
    dynamicRules.end = '666078a0';
  }

  return dynamicRules;
}

function createChecksum(shaHash: string): string {
  // rough but working reverse-engineered checksum creation for revision 202406051438-9d39aa517c
  const plus = (a: number, b: number) => a + b;
  const minus = (a: number, b: number) => a - b;
  const mod = (a: number, b: number) => a % b;
  return Math['abs'](
    plus(
      plus(
        plus(
          plus(
            plus(
              plus(
                plus(
                  plus(
                    plus(
                      plus(
                        plus(
                          plus(
                            plus(
                              plus(
                                plus(
                                  plus(
                                    plus(
                                      plus(
                                        plus(
                                          plus(
                                            plus(
                                              plus(
                                                plus(
                                                  plus(
                                                    plus(
                                                      plus(
                                                        shaHash[mod(26185, shaHash.length)].charCodeAt(0),
                                                        87
                                                      ) + minus(
                                                        shaHash[mod(26667, shaHash.length)].charCodeAt(0),
                                                        86
                                                      ),
                                                      shaHash[mod(27308, shaHash.length)].charCodeAt(0) + 92
                                                    ),
                                                    shaHash[mod(26767, shaHash.length)].charCodeAt(0) + 115
                                                  ),
                                                  plus(shaHash[26259 % shaHash.length].charCodeAt(0), 93)
                                                ),
                                                plus(
                                                  shaHash[mod(25908, shaHash.length)].charCodeAt(0),
                                                  124
                                                )
                                              ) + minus(shaHash[24828 % shaHash.length].charCodeAt(0), 85),
                                              plus(
                                                shaHash[mod(26107, shaHash.length)].charCodeAt(0),
                                                125
                                              )
                                            ) + plus(shaHash[25073 % shaHash.length].charCodeAt(0), 67),
                                            plus(
                                              shaHash[mod(25804, shaHash.length)].charCodeAt(0),
                                              62
                                            )
                                          ),
                                          minus(
                                            shaHash[mod(25263, shaHash.length)].charCodeAt(0),
                                            92
                                          )
                                        ),
                                        minus(
                                          shaHash[mod(26592, shaHash.length)].charCodeAt(0),
                                          99
                                        )
                                      ),
                                      minus(
                                        shaHash[mod(25754, shaHash.length)].charCodeAt(0),
                                        91
                                      )
                                    ),
                                    shaHash[mod(25468, shaHash.length)].charCodeAt(0) - 113
                                  ),
                                  minus(
                                    shaHash[mod(25138, shaHash.length)].charCodeAt(0),
                                    83
                                  )
                                ) + plus(shaHash[27390 % shaHash.length].charCodeAt(0), 112),
                                shaHash[26314 % shaHash.length].charCodeAt(0) - 65
                              ),
                              plus(shaHash[27228 % shaHash.length].charCodeAt(0), 138)
                            ),
                            shaHash[mod(26009, shaHash.length)].charCodeAt(0) - 126
                          ),
                          plus(shaHash[25383 % shaHash.length].charCodeAt(0), 127)
                        ),
                        shaHash[mod(25689, shaHash.length)].charCodeAt(0) + 137
                      ),
                      plus(
                        shaHash[mod(25023, shaHash.length)].charCodeAt(0),
                        141
                      )
                    ),
                    shaHash[26493 % shaHash.length].charCodeAt(0) - 130
                  ),
                  shaHash[mod(24771, shaHash.length)].charCodeAt(0) - 124
                ),
                minus(shaHash[27118 % shaHash.length].charCodeAt(0), 127)
              ) + (
                shaHash[mod(26392, shaHash.length)].charCodeAt(0) + 102
              ),
              minus(shaHash[26949 % shaHash.length].charCodeAt(0), 90)
            ),
            minus(
              shaHash[mod(24913, shaHash.length)].charCodeAt(0),
              102
            )
          ),
          plus(
            shaHash[mod(25186, shaHash.length)].charCodeAt(0),
            50
          )
        ) + (
          shaHash[mod(26864, shaHash.length)].charCodeAt(0) - 113
        ),
        minus(
          shaHash[mod(25577, shaHash.length)].charCodeAt(0),
          118
        )
      ),
      plus(
        shaHash[mod(27005, shaHash.length)].charCodeAt(0),
        85
      )
    )
  ) ['toString'](16)
}

generateHeaders('https://onlyfans.com/api2/v2/subscriptions/subscribes?offset=0&type=all&limit=10&format=infinite', '394914176').then(console.log)
```

**Comment by gangster665** [comment]
> This change only happened about 24 hours ago, no update was needed in the other 2 months. Maybe the project is abandoned, maybe not but it's too soon to tell.
> 
> In any case, I have a quick fix in a NodeJS/Typescript example. It's a bit rough but it works with the current revision
> 
> ```ts
> import { createHash } from 'crypto';
> 
> async function generateHeaders(fullUrl: string, userId: string) {
>   const dynamicRules = await getDynamicRules();
>   const time = +new Date()
>   const url = new URL(fullUrl)
>   const msg = [
>       dynamicRules["static_param"],
>       time,
>       url.pathname + url.search,
>       userId
>   ].join("\n")
>   const shaHash = createHash('sha1').update(msg).digest('hex');
> 
>   const checksum = createChecksum(shaHash);
>   const sign = [dynamicRules["start"], shaHash, checksum, dynamicRules["end"]].join(":")
>   // output: {sign, time}
>   return {sign, time};
> }
> 
> async function getDynamicRules(): Promise<any> {
>   const body = await fetch('https://raw.githubusercontent.com/deviint/onlyfans-dynamic-rules/main/dynamicRules.json');
>   let dynamicRules = await body.json();
>   if (dynamicRules.revision !== '202406051438-9d39aa517c') {
>     dynamicRules.start = '24650';
>     dynamicRules.static_param = 'RPnq8UadKceN7JNbeh2ApmUxM0A2nU9y';
>     dynamicRules.end = '666078a0';
>   }
> 
>   return dynamicRules;
> }
> 
> function createChecksum(shaHash: string): string {
>   // rough but working reverse-engineered checksum creation for revision 202406051438-9d39aa517c
>   const plus = (a: number, b: number) => a + b;
>   const minus = (a: number, b: number) => a - b;
>   const mod = (a: number, b: number) => a % b;
>   return Math['abs'](
>     plus(
>       plus(
>         plus(
>           plus(
>             plus(
>               plus(
>                 plus(
>                   plus(
>                     plus(
>                       plus(
>                         plus(
>                           plus(
>                             plus(
>                               plus(
>                                 plus(
>                                   plus(
>                                     plus(
>                                       plus(
>                                         plus(
>                                           plus(
>                                             plus(
>                                               plus(
>                                                 plus(
>                                                   plus(
>                                                     plus(
>                                                       plus(
>                                                         shaHash[mod(26185, shaHash.length)].charCodeAt(0),
>                                                         87
>                                                       ) + minus(
>                                                         shaHash[mod(26667, shaHash.length)].charCodeAt(0),
>                                                         86
>                                                       ),
>                                                       shaHash[mod(27308, shaHash.length)].charCodeAt(0) + 92
>                                                     ),
>                                                     shaHash[mod(26767, shaHash.length)].charCodeAt(0) + 115
>                                                   ),
>                                                   plus(shaHash[26259 % shaHash.length].charCodeAt(0), 93)
>                                                 ),
>                                                 plus(
>                                                   shaHash[mod(25908, shaHash.length)].charCodeAt(0),
>                                                   124
>                                                 )
>                                               ) + minus(shaHash[24828 % shaHash.length].charCodeAt(0), 85),
>                                               plus(
>                                                 shaHash[mod(26107, shaHash.length)].charCodeAt(0),
>                                                 125
>                                               )
>                                             ) + plus(shaHash[25073 % shaHash.length].charCodeAt(0), 67),
>                                             plus(
>                                               shaHash[mod(25804, shaHash.length)].charCodeAt(0),
>                                               62
>                                             )
>                                           ),
>                                           minus(
>                                             shaHash[mod(25263, shaHash.length)].charCodeAt(0),
>                                             92
>                                           )
>                                         ),
>                                         minus(
>                                           shaHash[mod(26592, shaHash.length)].charCodeAt(0),
>                                           99
>                                         )
>                                       ),
>                                       minus(
>                                         shaHash[mod(25754, shaHash.length)].charCodeAt(0),
>                                         91
>                                       )
>                                     ),
>                                     shaHash[mod(25468, shaHash.length)].charCodeAt(0) - 113
>                                   ),
>                                   minus(
>                                     shaHash[mod(25138, shaHash.length)].charCodeAt(0),
>                                     83
>                                   )
>                                 ) + plus(shaHash[27390 % shaHash.length].charCodeAt(0), 112),
>                                 shaHash[26314 % shaHash.length].charCodeAt(0) - 65
>                               ),
>                               plus(shaHash[27228 % shaHash.length].charCodeAt(0), 138)
>                             ),
>                             shaHash[mod(26009, shaHash.length)].charCodeAt(0) - 126
>                           ),
>                           plus(shaHash[25383 % shaHash.length].charCodeAt(0), 127)
>                         ),
>                         shaHash[mod(25689, shaHash.length)].charCodeAt(0) + 137
>                       ),
>                       plus(
>                         shaHash[mod(25023, shaHash.length)].charCodeAt(0),
>                         141
>                       )
>                     ),
>                     shaHash[26493 % shaHash.length].charCodeAt(0) - 130
>                   ),
>                   shaHash[mod(24771, shaHash.length)].charCodeAt(0) - 124
>                 ),
>                 minus(shaHash[27118 % shaHash.length].charCodeAt(0), 127)
>               ) + (
>                 shaHash[mod(26392, shaHash.length)].charCodeAt(0) + 102
>               ),
>               minus(shaHash[26949 % shaHash.length].charCodeAt(0), 90)
>             ),
>             minus(
>               shaHash[mod(24913, shaHash.length)].charCodeAt(0),
>               102
>             )
>           ),
>           plus(
>             shaHash[mod(25186, shaHash.length)].charCodeAt(0),
>             50
>           )
>         ) + (
>           shaHash[mod(26864, shaHash.length)].charCodeAt(0) - 113
>         ),
>         minus(
>           shaHash[mod(25577, shaHash.length)].charCodeAt(0),
>           118
>         )
>       ),
>       plus(
>         shaHash[mod(27005, shaHash.length)].charCodeAt(0),
>         85
>       )
>     )
>   ) ['toString'](16)
> }
> 
> generateHeaders('https://onlyfans.com/api2/v2/subscriptions/subscribes?offset=0&type=all&limit=10&format=infinite', '394914176').then(console.log)
> ```

This doesn't work anymore. Any updates pls?

**Comment by Manual3661** [comment]
@gangster665 still works for me, but if you have trouble, I noticed someone has updated the rules in a pull request.
If you can't wait, you can use his version which also seems to be working

https://github.com/deviint/onlyfans-dynamic-rules/pull/14

**Comment by gangster665** [comment]
@rafa-9
@Tg00174
@xafable
@Manual3661
guys i found working dynamic rules here
https://github.com/Growik/onlyfans-dynamic-rules/blob/main/rules.json
also repo seems to be constantly updated

**Comment by renzyndrome** [comment]
> @rafa-9 @Tg00174 @xafable @Manual3661 guys i found working dynamic rules here https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json also repo seems to be constantly updated

Hi, I tried this but it also gives me this error:

`data: { error: { code: 401, message: 'Please refresh the page' } }`

**Comment by gangster665** [comment]
@renzyndrome rules were recently updated and are working fine for me. So i think there is an issue in your code. If you can share it ill try to help

**Comment by bollerdominik** [comment]
> @rafa-9 @Tg00174 @xafable @Manual3661 guys i found working dynamic rules here https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json also repo seems to be constantly updated

I think Growik deleted the repository :( is there a new one?

**Comment by xagler** [comment]
> > @rafa-9 @Tg00174 @xafable @Manual3661 guys i found working dynamic rules here https://raw.githubusercontent.com/Growik/onlyfans-dynamic-rules/main/rules.json also repo seems to be constantly updated
> 
> I think Growik deleted the repository :( is there a new one?

https://github.com/xagler/dynamic-rules

**Comment by renzyndrome** [comment]
These new values from datawhores are working

https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/new/dynamicRules.json

**Comment by deviint** [comment]
This repo will continue to be maintained, and I want to thank all of the people who are supporting the ongoing updates and developments by purchasing tokens for [ofapi.xyz](https://ofapi.xyz).
