### ISSUE TITLE
Signing mechanism is not working for init and me endpoints

### ISSUE THREAD

**Issue by MrRedbloX** [deviint/onlyfans-dynamic-rules#3]
Hello,
It seems the signing mechanism for the /api2/v2/init and /api2/v2/users/me is a bit different from the rest.
Do you know what are they using?
Thanks.

**Comment by deviint** [comment]
I'm not sure what you mean. What are you seeing?

**Comment by MrRedbloX** [comment]
Yes so if we take the following parameters:
```
userId = "59450453"
time = "1674767222478"
url = "/api2/v2/stories"
```
We get a `shaHash` equals to `a93510b5cf3ef8224560a9d912199ad0f3786334` which is correct (I see the same on OnlyFans).
But if we take:
```
userId = "59450453"
time = "1674778089105"
url = "/api2/v2/init"
```
We get a `shaHash` equals to `6e7864ba516d7d9e6c8ee8b8f0a9a54a12a4a836` but what I see in OnlyFans is `64cdeeea373e1bc09b72f0873a621df83c1914f6`.
So I think they use a different mechanism to sign those kind of requests. A clue could be that they do not pass a `user-id` header in the `/api2/v2/init` request but they do in the `/api2/v2/stories` request.
Does that make sense? (Thanks for the quick reply btw).

**Comment by SneakyOvis** [comment]
Just use 0 as userId for /init, if I remember correctly. Try it :)

**Comment by MrRedbloX** [comment]
That's correct, thanks!
