### ISSUE TITLE
List of onlyfans api calls?

### ISSUE THREAD

**Issue by Shashank003** [deviint/onlyfans-dynamic-rules#4]
Do you have a list of onlyfans api calls? I would love to collaborate with you in building onlyfans tools.

**Comment by nuvenZA** [comment]
I am also seeking some assistance and willing to contribute payment to information to get a working way to conduct API calls.

**Comment by deviint** [comment]
> I am also seeking some assistance and willing to contribute payment to information to get a working way to conduct API calls.

DM me on Twitter
