### ISSUE TITLE
How are the dynamic rules updated?

### ISSUE THREAD

**Issue by adam-simple** [deviint/onlyfans-dynamic-rules#5]
Great job on this. I'm wondering how you keep the dynamic rules up to date? I'd like to do this on my own for my personal project so I can guarantee it's current at the time of sending requests. The workflow I'm using can't afford to be sometimes stale by 1 hour.

Thanks!

**Comment by deviint** [comment]
> Great job on this. I'm wondering how you keep the dynamic rules up to date? I'd like to do this on my own for my personal project so I can guarantee it's current at the time of sending requests. The workflow I'm using can't afford to be sometimes stale by 1 hour.
> 
> 
> 
> Thanks!

DM me on Twitter

**Comment by adam-simple** [comment]
> > Great job on this. I'm wondering how you keep the dynamic rules up to date? I'd like to do this on my own for my personal project so I can guarantee it's current at the time of sending requests. The workflow I'm using can't afford to be sometimes stale by 1 hour.
> > Thanks!
> 
> DM me on Twitter

done
