### ISSUE TITLE
GPT chat connecting to a website

### ISSUE THREAD

**Issue by doctorregina** [deviint/onlyfans-dynamic-rules#8]
Hiii,

I have an OnlyFans agency and I would be happy to build Java or Python script to automate chatting with costumers via GPT chat.
Could you please help me to create this code? As far as I know there are some difficulties with API in Onlyfans website so the data could only be transferred by data scrapping, am I right?

**Comment by deviint** [comment]
Hello, please send me an email at deviint@protonmail.com

GitHub is not meant for this kind of thing :)
